language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "7"
  - "node"
script:
  - yarn lint
  - yarn test
after_success:
  - "nyc report --reporter=text-lcov | coveralls"
